/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPenjualan;

/**
 *
 * @author Asus
 */
public class FormFAQ extends javax.swing.JFrame {

    /**
     * Creates new form FormFAQ
     */
    public FormFAQ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelTotal8 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelTotal1 = new javax.swing.JLabel();
        labelTotal2 = new javax.swing.JLabel();
        labelTotal3 = new javax.swing.JLabel();
        labelTotal4 = new javax.swing.JLabel();
        labelTotal5 = new javax.swing.JLabel();
        labelTotal6 = new javax.swing.JLabel();
        labelTotal7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        labelTotal8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTotal8.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal8.setText("Jika ada yang ingin ditanyakan lebih lanjut bisa menghubungi via instagram : @wildanlh__");
        labelTotal8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal.setText("Apa itu Lot?");
        labelTotal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelTotal1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTotal1.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal1.setText("Apa itu Saham?");
        labelTotal1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelTotal2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTotal2.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal2.setText("Saham adalah bukti kepemilikan nilai sebuah perusahaan atau bukti penyertaan modal.");
        labelTotal2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelTotal3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTotal3.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal3.setText("Lot merupakan satuan resmi yang telah ditetapkan oleh Bursa Efek Indonesia (BEI) dalam transaksi  jual beli saham. Mungkin masih ada yang bertanya 1 lot berapa lembar saham?  Mengacu pada aturan BEI, 1 lot setara dengan 100 lembar saham");
        labelTotal3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelTotal4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTotal4.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal4.setText("Apakah kita dapat melihat keuntungan atau kerugian?");
        labelTotal4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelTotal5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTotal5.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal5.setText("Tentu saja bisa, anda dapat melihatnya di Print Button form Jual Saham, namun sebelum itu anda harus memasukkan saham yang ingin anda jual.");
        labelTotal5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelTotal6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTotal6.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal6.setText("Mengapa harga saham tidak berubah?");
        labelTotal6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelTotal7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTotal7.setForeground(new java.awt.Color(51, 102, 204));
        labelTotal7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal7.setText("Aplikasi ini ditujukan untuk mensimulasikan ketika anda ingin mencoba dalam dunia saham, serta aplikasi ini tidak bisa terhubung ke saham aslinya.");
        labelTotal7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jPanel1.setBackground(new java.awt.Color(51, 102, 204));
        jPanel1.setForeground(new java.awt.Color(51, 102, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-bubble-question-icon64.png"))); // NOI18N
        jLabel2.setText("FAQ (Frequently Asked Questions)");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (1).png"))); // NOI18N
        jLabel14.setText("Menu");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelTotal8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 1669, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTotal7, javax.swing.GroupLayout.PREFERRED_SIZE, 1669, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 1669, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(labelTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTotal8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        MenuPenjualan au = new MenuPenjualan();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFAQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFAQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotal1;
    private javax.swing.JLabel labelTotal2;
    private javax.swing.JLabel labelTotal3;
    private javax.swing.JLabel labelTotal4;
    private javax.swing.JLabel labelTotal5;
    private javax.swing.JLabel labelTotal6;
    private javax.swing.JLabel labelTotal7;
    private javax.swing.JLabel labelTotal8;
    // End of variables declaration//GEN-END:variables
}
