/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPenjualan;

import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Asus
 */
public class MenuPenjualan extends javax.swing.JFrame {

    /**
     * Creates new form MenuPenjualan
     */
    public MenuPenjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuAkun = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuPelanggan = new javax.swing.JMenuItem();
        menuBarang = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuPembelian = new javax.swing.JMenuItem();
        menuPenjualan = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuLBarang = new javax.swing.JMenuItem();
        menuLPelanggan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuseparatorTransaksi = new javax.swing.JMenu();
        menuPembelian1 = new javax.swing.JMenuItem();
        menuPenjualan1 = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuFaq = new javax.swing.JMenuItem();
        menuPanduan = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        menuAbout1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 102, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tokosahamlogo-unscreen.gif"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TOKO SAHAM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel10)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        menuHome.setBackground(new java.awt.Color(255, 255, 255));
        menuHome.setForeground(new java.awt.Color(51, 102, 204));
        menuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon 48px.png"))); // NOI18N
        menuHome.setText("Home");
        menuHome.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        menuAkun.setBackground(new java.awt.Color(255, 255, 255));
        menuAkun.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuAkun.setForeground(new java.awt.Color(51, 102, 204));
        menuAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-icon 48px.png"))); // NOI18N
        menuAkun.setText("Akun");
        menuAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAkunActionPerformed(evt);
            }
        });
        menuHome.add(menuAkun);

        jMenuBar1.add(menuHome);

        menuMaster.setBackground(new java.awt.Color(255, 255, 255));
        menuMaster.setForeground(new java.awt.Color(51, 102, 204));
        menuMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/archive-icon 48px.png"))); // NOI18N
        menuMaster.setText("Master");
        menuMaster.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        menuPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        menuPelanggan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuPelanggan.setForeground(new java.awt.Color(51, 102, 204));
        menuPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/identity-card-icon 48px.png"))); // NOI18N
        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        menuMaster.add(menuPelanggan);

        menuBarang.setBackground(new java.awt.Color(255, 255, 255));
        menuBarang.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuBarang.setForeground(new java.awt.Color(51, 102, 204));
        menuBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database-icon 48px.png"))); // NOI18N
        menuBarang.setText("Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        menuMaster.add(menuBarang);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        menuTransaksi.setForeground(new java.awt.Color(51, 102, 204));
        menuTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calculator-icon 48px.png"))); // NOI18N
        menuTransaksi.setText("Transaksi");
        menuTransaksi.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });

        menuPembelian.setBackground(new java.awt.Color(255, 255, 255));
        menuPembelian.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuPembelian.setForeground(new java.awt.Color(51, 102, 204));
        menuPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shopping-cart-icon 48px.png"))); // NOI18N
        menuPembelian.setText("Pembelian");
        menuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembelianActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuPembelian);

        menuPenjualan.setBackground(new java.awt.Color(255, 255, 255));
        menuPenjualan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuPenjualan.setForeground(new java.awt.Color(51, 102, 204));
        menuPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shopping-basket-icon 48px.png"))); // NOI18N
        menuPenjualan.setText("Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuPenjualan);

        jMenuBar1.add(menuTransaksi);

        menuLaporan.setBackground(new java.awt.Color(255, 255, 255));
        menuLaporan.setForeground(new java.awt.Color(51, 102, 204));
        menuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-icon 48px.png"))); // NOI18N
        menuLaporan.setText("Laporan");
        menuLaporan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanActionPerformed(evt);
            }
        });

        menuLBarang.setBackground(new java.awt.Color(255, 255, 255));
        menuLBarang.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuLBarang.setForeground(new java.awt.Color(51, 102, 204));
        menuLBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/database-icon 48px.png"))); // NOI18N
        menuLBarang.setText("Barang");
        menuLBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLBarangActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLBarang);

        menuLPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        menuLPelanggan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuLPelanggan.setForeground(new java.awt.Color(51, 102, 204));
        menuLPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/identity-card-icon 48px.png"))); // NOI18N
        menuLPelanggan.setText("Pelanggan");
        menuLPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLPelangganActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLPelanggan);
        menuLaporan.add(jSeparator1);

        menuseparatorTransaksi.setForeground(new java.awt.Color(51, 102, 204));
        menuseparatorTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stats-icon 48px.png"))); // NOI18N
        menuseparatorTransaksi.setText("Transaksi");
        menuseparatorTransaksi.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        menuPembelian1.setBackground(new java.awt.Color(255, 255, 255));
        menuPembelian1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuPembelian1.setForeground(new java.awt.Color(51, 102, 204));
        menuPembelian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shopping-cart-icon 48px.png"))); // NOI18N
        menuPembelian1.setText("Pembelian");
        menuPembelian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembelian1ActionPerformed(evt);
            }
        });
        menuseparatorTransaksi.add(menuPembelian1);

        menuPenjualan1.setBackground(new java.awt.Color(255, 255, 255));
        menuPenjualan1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuPenjualan1.setForeground(new java.awt.Color(51, 102, 204));
        menuPenjualan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shopping-basket-icon 48px.png"))); // NOI18N
        menuPenjualan1.setText("Penjualan");
        menuPenjualan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualan1ActionPerformed(evt);
            }
        });
        menuseparatorTransaksi.add(menuPenjualan1);

        menuLaporan.add(menuseparatorTransaksi);

        jMenuBar1.add(menuLaporan);

        menuHelp.setBackground(new java.awt.Color(255, 255, 255));
        menuHelp.setForeground(new java.awt.Color(51, 102, 204));
        menuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-round-dark-question-icon48.png"))); // NOI18N
        menuHelp.setText("Help");
        menuHelp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        menuFaq.setBackground(new java.awt.Color(255, 255, 255));
        menuFaq.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuFaq.setForeground(new java.awt.Color(51, 102, 204));
        menuFaq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-bubble-question-icon48.png"))); // NOI18N
        menuFaq.setText("FAQ");
        menuFaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFaqActionPerformed(evt);
            }
        });
        menuHelp.add(menuFaq);

        menuPanduan.setBackground(new java.awt.Color(255, 255, 255));
        menuPanduan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuPanduan.setForeground(new java.awt.Color(51, 102, 204));
        menuPanduan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/diary-icon.png"))); // NOI18N
        menuPanduan.setText("Panduan");
        menuPanduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPanduanActionPerformed(evt);
            }
        });
        menuHelp.add(menuPanduan);

        menuAbout.setBackground(new java.awt.Color(255, 255, 255));
        menuAbout.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuAbout.setForeground(new java.awt.Color(51, 102, 204));
        menuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-round-info-icon 48px.png"))); // NOI18N
        menuAbout.setText("Tentang");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuAbout);

        jMenuBar1.add(menuHelp);

        menuLogout.setBackground(new java.awt.Color(255, 255, 255));
        menuLogout.setForeground(new java.awt.Color(51, 102, 204));
        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-round-power-icon 48px.png"))); // NOI18N
        menuLogout.setText("LogOut");
        menuLogout.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuLogoutKeyPressed(evt);
            }
        });

        menuAbout1.setBackground(new java.awt.Color(255, 255, 255));
        menuAbout1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        menuAbout1.setForeground(new java.awt.Color(51, 102, 204));
        menuAbout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button-round-cancel-icon48.png"))); // NOI18N
        menuAbout1.setText("Keluar");
        menuAbout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbout1ActionPerformed(evt);
            }
        });
        menuLogout.add(menuAbout1);

        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembelianActionPerformed
        // TODO add your handling code here:
        FormPembelian au = new FormPembelian();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPembelianActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        // TODO add your handling code here:
        FormPelanggan au = new FormPelanggan();
        au.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        // TODO add your handling code here:
        FormBarang au = new FormBarang();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        // TODO add your handling code here:
        FormPenjualan au = new FormPenjualan();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuLPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLPelangganActionPerformed
        // TODO add your handling code here:
        try{
            String file = "/Report/DataPelanggan.jasper";
            JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream(file),null,koneksi.getKoneksi());
            JasperViewer.viewReport(print, false);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        
        }
    }//GEN-LAST:event_menuLPelangganActionPerformed

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed
        // TODO add your handling code here:
        FormPenjualan au = new FormPenjualan();
        au.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_menuTransaksiActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuLogoutKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_menuLogoutKeyPressed

    private void menuAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAkunActionPerformed
        // TODO add your handling code here:
        FormAkun au = new FormAkun();
        au.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_menuAkunActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
        FormAbout au = new FormAbout();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuFaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFaqActionPerformed
        // TODO add your handling code here:
        FormFAQ au = new FormFAQ();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuFaqActionPerformed

    private void menuLBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLBarangActionPerformed
        // TODO add your handling code here:
        try{
            String file = "/Report/DataBarang.jasper";
            JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream(file),null,koneksi.getKoneksi());
            JasperViewer.viewReport(print, false);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        
        }
    }//GEN-LAST:event_menuLBarangActionPerformed

    private void menuPanduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPanduanActionPerformed
        // TODO add your handling code here:
         FormGuide au = new FormGuide();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPanduanActionPerformed

    private void menuAbout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbout1ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar?", "Toko Saham", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
             MenuPenjualan au = new MenuPenjualan();
             au.setVisible(true);
             this.setVisible(false);
  }
    }//GEN-LAST:event_menuAbout1ActionPerformed

    private void menuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLaporanActionPerformed

    private void menuPembelian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembelian1ActionPerformed
        // TODO add your handling code here:
        FormLaporanPembelian au = new FormLaporanPembelian();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPembelian1ActionPerformed

    private void menuPenjualan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualan1ActionPerformed
        // TODO add your handling code here:
        FormLaporanPenjualan au = new FormLaporanPenjualan();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPenjualan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuAbout1;
    private javax.swing.JMenuItem menuAkun;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuFaq;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menuLBarang;
    private javax.swing.JMenuItem menuLPelanggan;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuPanduan;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem menuPembelian;
    private javax.swing.JMenuItem menuPembelian1;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenuItem menuPenjualan1;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenu menuseparatorTransaksi;
    // End of variables declaration//GEN-END:variables
}
